#!/usr/bin/env bash

set -e

podman build \
  --build-arg BASE_IMAGE=debian \
  --build-arg PKG_MANAGER=apt \
  --build-arg PKGS="\
        attr \
        autoconf \
        automake \
        autopoint \
        bison \
        btrfs-progs \
        cpio \
        cryptsetup \
        dosfstools \
        e2fsprogs \
        erofs-utils \
        exfatprogs \
        f2fs-tools \
        flex \
        gawk \
        genromfs \
        gettext \
        git \
        hfsplus \
        jfsutils \
        libtool \
        lzop \
        make \
        mtools \
        nilfs-tools \
        ntfs-3g \
        ovmf \
        ovmf-ia32 \
        parted \
        patch \
        pkg-config \
        python3 \
        qemu-efi-aarch64 \
        qemu-efi-arm \
        qemu-system \
	rsync \
        squashfs-tools \
        swtpm-tools \
        texinfo \
        texlive \
        tpm2-tools \
        udftools \
        unifont \
        wamerican \
        which \
        xfonts-unifont \
        xfsprogs \
        xorriso \
        zfs-fuse" \
  -t debian-grub .

podman run -it debian-grub
