define(`IMAGE',`dnl
FROM $1

RUN PKG_MNG PKG_MNG_UPDATE_ARGS
RUN PKG_MNG PKG_MNG_INSTALL_ARGS PKGS
RUN git clone GRUB_CLONE_DEPTH GRUB_REPO GRUB_DIR

COPY GRUB_BUILD_SCRIPT .
RUN chmod +x GRUB_BUILD_SCRIPT')
